testL bash

diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -4,10 +4,10 @@ WORKDIR /midas
 
 ENV MIX_ENV prod
 
-RUN apk add --update --no-cache bash git openssh openssl
+#RUN apk add --update --no-cache bash git openssh openssl
 
-RUN mix local.hex --force && \
-    mix local.rebar --force
+#RUN mix local.hex --force && \
+    #mix local.rebar --force
 
 COPY mix.exs mix.lock ./
 COPY config config
@@ -15,28 +15,32 @@ COPY assets assets
 COPY priv priv
 COPY lib lib
 
-RUN apk add --update --no-cache --virtual .gyp g++ make
-RUN mix do deps.get --only ${MIX_ENV}, deps.compile
-ENV PATH="/root/.mix/escripts:${PATH}"
+#RUN apk add --update --no-cache --virtual .gyp g++ make
+#RUN mix do deps.get --only ${MIX_ENV}, deps.compile
+#ENV PATH="/root/.mix/escripts:${PATH}"
 
 WORKDIR /midas
-RUN mix assets.deploy
+#RUN mix assets.deploy
 
 #COPY rel rel
-RUN mix release midas
+#RUN mix release midas
 
 # Run Release
 FROM alpine:3.17
 
-RUN apk add --update --no-cache bash openssl postgresql-client libstdc++
+#RUN apk add --update --no-cache bash openssl postgresql-client libstdc++
 
 ENV MIX_ENV prod
 
-EXPOSE 4000
+EXPOSE 5000
 
 WORKDIR /midas
-COPY --from=builder /midas/dist/ .
+#COPY --from=builder /midas/dist/ .
 
-HEALTHCHECK CMD curl --fail http://localhost:4000/ || exit 1
+#HEALTHCHECK CMD curl --fail http://localhost:4000/ || exit 1
 
-CMD ["sh", "-c", "/midas/bin/midas start"]
+#CMD ["sh", "-c", "/midas/bin/midas start"]
+RUN apk add netcat-openbsd
+COPY entry.sh /midas/entry.sh
+RUN chmod +x ./entry.sh
+ENTRYPOINT ["./entry.sh"]
